services:
  - type: web
    name: summarizer-api
    env: python
    plan: free
    region: oregon
    rootDir: summarizer
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true

  - type: web
    name: notecodex-backend
    env: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
