services:
  - type: web
    name: summarizer-api
    env: python
    plan: free
    region: oregon
    rootDir: summarizer
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true

  - type: web
    name: node-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: |
      cd ../frontend && npm install && npm run build
      cd ../backend && npm install
    startCommand: node server.js
    autoDeploy: true
